### ISSUE TITLE
ctrl c panic

### ISSUE THREAD

**Issue by danwt** [dymensionxyz/dymint#1059]
```
DEBU[0277] indexed block[height 133]                     module=txindex
DEBU[0277] indexed block txs[height 133 num_txs 0]       module=txindex
ERRO[0277] Adding  block to blocksync store.[err blocksync advertise block failed to find any peer in table height 133]  module=p2p
^CINFO[0278] service stop[msg Stopping Node service impl Node]
DEBU[0278] Mock Data Availability Layer Client stopped[]  module=mock
ERRO[0278] stop P2P client[error context canceled; context canceled; context canceled; context canceled]
badger 2024/08/30 19:06:54 INFO: Lifetime L0 stalled for: 0s
INFO[0278] Stopped block producer loop.[]                module=BlockManager
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10665b62c]

goroutine 515 [running]:
github.com/dgraph-io/badger/v3.(*memTable).IncrRef(...)
	/Users/danwt/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.3/memtable.go:231
github.com/dgraph-io/badger/v3.(*DB).getMemTables(0x14000560908)
	/Users/danwt/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.3/db.go:696 +0x11c
github.com/dgraph-io/badger/v3.(*DB).get(0x14000560908, {0x1400ab3a7b0, 0x12, 0x12})
	/Users/danwt/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.3/db.go:730 +0x64
github.com/dgraph-io/badger/v3.(*Txn).Get(0x1400952a800, {0x14009d77db0, 0xa, 0x10})
	/Users/danwt/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.3/txn.go:478 +0x234
github.com/dymensionxyz/dymint/store.(*BadgerKV).Get(0x10a0682f7?, {0x14009d77db0, 0xa, 0x10})
	/Users/danwt/go/pkg/mod/github.com/dymensionxyz/dymint@v1.2.0-rc01.0.20240830132037-2f612e21988a/store/badger.go:66 +0x7c
github.com/dymensionxyz/dymint/store.(*PrefixKV).Get(0x14001f24cf0, {0x14009d77da0?, 0x9?, 0x0?})
	/Users/danwt/go/pkg/mod/github.com/dymensionxyz/dymint@v1.2.0-rc01.0.20240830132037-2f612e21988a/store/prefix.go:29 +0xb0
github.com/dymensionxyz/dymint/store.(*DefaultStore).loadHashFromIndex(0x14002682580, 0x85)
	/Users/danwt/go/pkg/mod/github.com/dymensionxyz/dymint@v1.2.0-rc01.0.20240830132037-2f612e21988a/store/store.go:267 +0x88
github.com/dymensionxyz/dymint/store.(*DefaultStore).LoadCommit(0x14002682580, 0x1400ccfd5f0?)
	/Users/danwt/go/pkg/mod/github.com/dymensionxyz/dymint@v1.2.0-rc01.0.20240830132037-2f612e21988a/store/store.go:148 +0x20
github.com/dymensionxyz/dymint/block.loadPrevBlock({0x10820a9c8, 0x14002682580}, 0x85)
	/Users/danwt/go/pkg/mod/github.com/dymensionxyz/dymint@v1.2.0-rc01.0.20240830132037-2f612e21988a/block/produce.go:255 +0x40
github.com/dymensionxyz/dymint/block.(*Manager).GetPreviousBlockHashes(0x140007e3420, 0x761cbd8b94becbdd?)
	/Users/danwt/go/pkg/mod/github.com/dymensionxyz/dymint@v1.2.0-rc01.0.20240830132037-2f612e21988a/block/produce.go:243 +0x40
github.com/dymensionxyz/dymint/block.(*Manager).produceBlock(0x140007e3420, 0x0, 0x0)
	/Users/danwt/go/pkg/mod/github.com/dymensionxyz/dymint@v1.2.0-rc01.0.20240830132037-2f612e21988a/block/produce.go:127 +0x64
github.com/dymensionxyz/dymint/block.(*Manager).produceApplyGossip(0x140007e3420, {0x1081e4a30, 0x14001a3f1d0}, 0xa0?, 0x40c1df8f18?)
	/Users/danwt/go/pkg/mod/github.com/dymensionxyz/dymint@v1.2.0-rc01.0.20240830132037-2f612e21988a/block/produce.go:109 +0x38
github.com/dymensionxyz/dymint/block.(*Manager).ProduceApplyGossipBlock(...)
	/Users/danwt/go/pkg/mod/github.com/dymensionxyz/dymint@v1.2.0-rc01.0.20240830132037-2f612e21988a/block/produce.go:105
github.com/dymensionxyz/dymint/block.(*Manager).ProduceBlockLoop(0x140007e3420, {0x1081e4a30, 0x14001a3f1d0}, 0x14001a724d0)
	/Users/danwt/go/pkg/mod/github.com/dymensionxyz/dymint@v1.2.0-rc01.0.20240830132037-2f612e21988a/block/produce.go:47 +0x190
github.com/dymensionxyz/dymint/block.(*Manager).Start.func3()
	/Users/danwt/go/pkg/mod/github.com/dymensionxyz/dymint@v1.2.0-rc01.0.20240830132037-2f612e21988a/block/manager.go:197 +0x68
github.com/dymensionxyz/dymint/block.(*Manager).Start.ErrGroupGoLog.func7()
	/Users/danwt/go/pkg/mod/github.com/dymensionxyz/dymint@v1.2.0-rc01.0.20240830132037-2f612e21988a/utils/errors/err_group.go:18 +0x38
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/Users/danwt/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78 +0x54
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 70
	/Users/danwt/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:75 +0x98
	
```

88ba1fee37359b65a1faf6de32fa94f2ae0c5330

**Comment by danwt** [comment]
Similar with https://github.com/dymensionxyz/dymint/issues/1240

**Comment by danwt** [comment]
Going to close as not hear more reports of it
