### ISSUE TITLE
Dymint fails to sync to latest state

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/dymint#496]
```
time="2023-09-28T15:57:28+02:00" level=info msg="starting node with ABCI dymint in-process[]"
time="2023-09-28T15:57:28+02:00" level=info msg="service start[msg Starting multiAppConn service impl multiAppConn]" module=proxy
time="2023-09-28T15:57:28+02:00" level=info msg="service start[msg Starting localClient service impl localClient]" connection=query module=abci-client
time="2023-09-28T15:57:28+02:00" level=info msg="service start[msg Starting localClient service impl localClient]" connection=snapshot module=abci-client
time="2023-09-28T15:57:28+02:00" level=info msg="service start[msg Starting localClient service impl localClient]" connection=mempool module=abci-client
time="2023-09-28T15:57:28+02:00" level=info msg="service start[msg Starting localClient service impl localClient]" connection=consensus module=abci-client
time="2023-09-28T15:57:28+02:00" level=info msg="service start[msg Starting EventBus service impl EventBus]" module=events
time="2023-09-28T15:57:28+02:00" level=info msg="service start[msg Starting PubSub service impl PubSub]" module=pubsub
badger 2023/09/28 15:57:28 INFO: All 10 tables opened in 1ms
badger 2023/09/28 15:57:28 INFO: Discard stats nextEmptySlot: 0
badger 2023/09/28 15:57:28 INFO: Set nextTxnTs to 27906
badger 2023/09/28 15:57:28 INFO: Deleting empty file: /root/.roller/rollapp/data/dymint/004089.vlog
time="2023-09-28T15:57:28+02:00" level=debug msg="Getting latest batch from settlement layer[]" module=settlement_client
time="2023-09-28T15:57:28+02:00" level=info msg="Updated latest height from settlement layer[latestHeight 341]" module=settlement_client
time="2023-09-28T15:57:28+02:00" level=info msg="Updated sequencers list from settlement layer[sequencersList [0xc0039be528]]" module=settlement_client
time="2023-09-28T15:57:28+02:00" level=info msg="service start[msg Starting IndexerService service impl IndexerService]" module=txindex
time="2023-09-28T15:57:28+02:00" level=info msg="service start[msg Starting RPC service impl RPC]"
time="2023-09-28T15:57:28+02:00" level=debug msg="limiting number of connections[limit 900]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name status]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name abci_query]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name abci_info]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name unsubscribe]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name genesis_chunked]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name broadcast_tx_commit]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name block_by_hash]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name dump_consensus_state]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name broadcast_tx_sync]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name num_unconfirmed_txs]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name broadcast_tx_async]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name unsubscribe_all]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name health]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name genesis]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name block_results]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name broadcast_evidence]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name subscribe]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name blockchain]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name block]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name check_tx]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name validators]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name consensus_state]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name commit]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name tx]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name block_search]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name unconfirmed_txs]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name net_info]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name tx_search]"
time="2023-09-28T15:57:28+02:00" level=debug msg="registering method[name consensus_params]"
time="2023-09-28T15:57:28+02:00" level=debug msg="CORS enabled[origins [*] methods [HEAD GET POST] headers [Origin Accept Content-Type X-Requested-With X-Server-Time]]"
time="2023-09-28T15:57:28+02:00" level=info msg="service start[msg Starting Node service impl Node]"
time="2023-09-28T15:57:28+02:00" level=info msg="starting P2P client[]"
time="2023-09-28T15:57:28+02:00" level=debug msg="starting P2P client[]" module=p2p
time="2023-09-28T15:57:28+02:00" level=info msg="serving HTTP[listen address [::]:46657]"
time="2023-09-28T15:57:28+02:00" level=info msg="listening on[address /ip4/65.109.89.147/tcp/46656/p2p/12D3KooWNeKVc5xkxEdR6rYmQWJfDzK4T9dGwdz4pyn1mJzUCC4i]" module=p2p
time="2023-09-28T15:57:28+02:00" level=info msg="listening on[address /ip4/127.0.0.1/tcp/46656/p2p/12D3KooWNeKVc5xkxEdR6rYmQWJfDzK4T9dGwdz4pyn1mJzUCC4i]" module=p2p
time="2023-09-28T15:57:28+02:00" level=debug msg="setting up gossiping[]" module=p2p
time="2023-09-28T15:57:28+02:00" level=debug msg="setting up DHT[]" module=p2p
time="2023-09-28T15:57:28+02:00" level=info msg="no seed nodes - only listening for connections[]" module=p2p
time="2023-09-28T15:57:28+02:00" level=debug msg="setting up active peer discovery[]" module=p2p
time="2023-09-28T15:57:28+02:00" level=info msg="starting Celestia Data Availability Layer Client[]" module=celestia
time="2023-09-28T15:57:28+02:00" level=debug msg="settlement Layer Client starting.[]" module=settlement_client
time="2023-09-28T15:57:28+02:00" level=info msg="started state updates handler loop[]" module=settlement_client
time="2023-09-28T15:57:29+02:00" level=info msg="Starting the block manager[]" module=BlockManager
time="2023-09-28T15:57:29+02:00" level=info msg="Starting in aggregator mode[]" module=BlockManager
time="2023-09-28T15:57:29+02:00" level=debug msg="Getting latest batch from settlement layer[]" module=settlement_client
time="2023-09-28T15:57:29+02:00" level=info msg="Started sync target loop[]" module=BlockManager
time="2023-09-28T15:57:29+02:00" level=debug msg="Getting latest batch from settlement layer[]" module=settlement_client
time="2023-09-28T15:57:29+02:00" level=info msg="Started retrieve loop[]" module=BlockManager
time="2023-09-28T15:57:29+02:00" level=debug msg="grpc client assigned to client context[target 127.0.0.1:4090]"
time="2023-09-28T15:57:29+02:00" level=info msg="serve[msg Starting RPC HTTP server on [::]:4317]" module=api-server
time="2023-09-28T15:57:29+02:00" level=info msg="Received new syncTarget[syncTarget 341]" module=BlockManager
time="2023-09-28T15:57:29+02:00" level=info msg="Waiting for sync[current height 339 syncTarget 341]" module=BlockManager
time="2023-09-28T15:57:29+02:00" level=info msg="Syncing until target[current height 339 syncTarget 341]" module=BlockManager
time="2023-09-28T15:57:29+02:00" level=debug msg="Getting batch from settlement layer[state index [116]]" module=settlement_client
time="2023-09-28T15:57:29+02:00" level=info msg="Received new syncTarget[syncTarget 341]" module=BlockManager
time="2023-09-28T15:57:29+02:00" level=debug msg="trying to retrieve batch from DA[daHeight 465629]" module=BlockManager
time="2023-09-28T15:57:29+02:00" level=debug msg="retrieved batches[n 1 daHeight 465629]" module=BlockManager
time="2023-09-28T15:57:29+02:00" level=debug msg="Applying block[height 340 source da]" module=BlockManager
time="2023-09-28T15:57:29+02:00" level=error msg="Failed to execute block[error AppHash mismatch]" module=BlockManager
time="2023-09-28T15:57:29+02:00" level=error msg="Failed to sync until target. error while processing next DA batch[error AppHash mismatch]" module=BlockManager
time="2023-09-28T15:57:29+02:00" level=info msg="Syncing until target[current height 339 syncTarget 341]" module=BlockManager
time="2023-09-28T15:57:29+02:00" level=debug msg="Getting batch from settlement layer[state index [116]]" module=settlement_client
time="2023-09-28T15:57:29+02:00" level=debug msg="trying to retrieve batch from DA[daHeight 465629]" module=BlockManager
time="2023-09-28T15:57:29+02:00" level=debug msg="retrieved batches[n 1 daHeight 465629]" module=BlockManager
time="2023-09-28T15:57:29+02:00" level=debug msg="Applying block[height 340 source da]" module=BlockManager
time="2023-09-28T15:57:29+02:00" level=error msg="Failed to execute block[error AppHash mismatch]" module=BlockManager
time="2023-09-28T15:57:29+02:00" level=error msg="Failed to sync until target. error while processing next DA batch[error AppHash mismatch]" module=BlockManager
time="2023-09-28T15:57:44+02:00" level=info msg="Starting JSON-RPC server[address 0.0.0.0:4545]"
time="2023-09-28T15:57:49+02:00" level=info msg="Starting JSON WebSocket server[address 0.0.0.0:4546]"
time="2023-09-28T15:59:09+02:00" level=info msg="Using pending block[height 340]" module=BlockManager
time="2023-09-28T15:59:09+02:00" level=debug msg="Gossiping block[len 10206]" module=p2p
time="2023-09-28T15:59:09+02:00" level=debug msg="Applying block[height 340 source produced]" module=BlockManager
time="2023-09-28T15:59:09+02:00" level=error msg="Failed to execute block[error AppHash mismatch]" module=BlockManager
time="2023-09-28T15:59:09+02:00" level=error msg="error while producing empty block[error AppHash mismatch]" module=BlockManager
time="2023-09-28T15:59:09+02:00" level=debug msg="Verifying last block in batch is an empty block[startHeight 342 endHeight 339 height]" module=BlockManager
panic: runtime error: makeslice: cap out of range

goroutine 355 [running]:
github.com/dymensionxyz/dymint/block.(*Manager).createNextDABatch(0xc00018ab00, 0x156, 0x153)
	/home/runner/go/pkg/mod/github.com/dymensionxyz/dymint@v0.5.1-rc01/block/manager.go:831 +0x57
github.com/dymensionxyz/dymint/block.(*Manager).submitNextBatch(0xc00018ab00, {0x31da503?, 0xc0000540d0?})
	/home/runner/go/pkg/mod/github.com/dymensionxyz/dymint@v0.5.1-rc01/block/manager.go:776 +0xbc
github.com/dymensionxyz/dymint/block.(*Manager).SubmitLoop(0xc00018ab00, {0x4049c78, 0xc0000540d0})
	/home/runner/go/pkg/mod/github.com/dymensionxyz/dymint@v0.5.1-rc01/block/manager.go:321 +0x2c5
created by github.com/dymensionxyz/dymint/block.(*Manager).Start
	/home/runner/go/pkg/mod/github.com/dymensionxyz/dymint@v0.5.1-rc01/block/manager.go:186 +0x16d
```

**Comment by mtsitrin** [comment]
> I moved all related folders to another server then start it with roller run


the user is using multiple servers, so this probably related

**Comment by omritoptix** [comment]
I believe the reset loop is because of it running part of systemd no?
If so - can we close it @mtsitrin ?
