### ISSUE TITLE
celestia da nil pointer error

### ISSUE THREAD

**Issue by srene** [dymensionxyz/dymint#799]
goroutine 62 [running]:
github.com/dymensionxyz/dymint/da/celestia.(*DataAvailabilityLayerClient).getDataAvailabilityHeaders(0x14000368c30, 0x14d1e6)
	/Users/sergi/workspace/dymension/dymint/da/celestia/celestia.go:646 +0x88
github.com/dymensionxyz/dymint/da/celestia.(*DataAvailabilityLayerClient).checkBatchAvailability(0x14000368c30, 0x1401d3ff960)
	/Users/sergi/workspace/dymension/dymint/da/celestia/celestia.go:454 +0xdc
github.com/dymensionxyz/dymint/da/celestia.(*DataAvailabilityLayerClient).CheckBatchAvailability.func1()
	/Users/sergi/workspace/dymension/dymint/da/celestia/celestia.go:426 +0x34
github.com/avast/retry-go/v4.Do.func1()
	/Users/sergi/go/pkg/mod/github.com/avast/retry-go/v4@v4.5.0/retry.go:115 +0x24
github.com/avast/retry-go/v4.DoWithData[...](0x1408dd91718?, {0x1408dd91810, 0x3, 0x7a})
	/Users/sergi/go/pkg/mod/github.com/avast/retry-go/v4@v4.5.0/retry.go:179 +0x564
github.com/avast/retry-go/v4.Do(0x0?, {0x1408dd91810?, 0x1408dd91778?, 0x10261c00c?})
	/Users/sergi/go/pkg/mod/github.com/avast/retry-go/v4@v4.5.0/retry.go:118 +0x4c
github.com/dymensionxyz/dymint/da/celestia.(*DataAvailabilityLayerClient).CheckBatchAvailability(0x14000368c30, 0x1401d3ff960)
	/Users/sergi/workspace/dymension/dymint/da/celestia/celestia.go:425 +0x110
github.com/dymensionxyz/dymint/block.(*Manager).fetchBatch(0x140014def08, 0x1401d3ff960)
	/Users/sergi/workspace/dymension/dymint/block/retriever.go:139 +0x184
github.com/dymensionxyz/dymint/block.(*Manager).ProcessNextDABatch(0x140014def08, 0x1401d3ff960)
	/Users/sergi/workspace/dymension/dymint/block/retriever.go:96 +0xd0
github.com/dymensionxyz/dymint/block.(*Manager).syncUntilTarget(0x140014def08, 0x265e1)
	/Users/sergi/workspace/dymension/dymint/block/retriever.go:57 +0x154
github.com/dymensionxyz/dymint/block.(*Manager).syncBlockManager(0x140014def08)
	/Users/sergi/workspace/dymension/dymint/block/manager.go:209 +0x9c
github.com/dymensionxyz/dymint/block.(*Manager).Start(0x140014def08, {0x1040f1d30, 0x105e92ce0}, 0x0)
	/Users/sergi/workspace/dymension/dymint/block/manager.go:177 +0x274
github.com/dymensionxyz/dymint/node.(*Node).OnStart(0x140008d1c08)
	/Users/sergi/workspace/dymension/dymint/node/node.go:316 +0x204
github.com/tendermint/tendermint/libs/service.(*BaseService).Start(0x140008d1c08)
	/Users/sergi/go/pkg/mod/github.com/cometbft/cometbft@v0.34.28/libs/service/service.go:144 +0x320
github.com/dymensionxyz/rollapp-evm/cmd/rollappd/cmd.startInProcess(_, {{0x0, 0x0, 0x0}, {0x1041240a0, 0x140015f4990}, 0x0, {0x14000821970, 0xa}, {0x104116c00, ...}, ...}, ...)
	/Users/sergi/workspace/dymension/rollapp-evm-2/cmd/rollappd/cmd/start.go:335 +0x824
github.com/dymensionxyz/rollapp-evm/cmd/rollappd/cmd.StartCmd.func2.1()
	/Users/sergi/workspace/dymension/rollapp-evm-2/cmd/rollappd/cmd/start.go:176 +0x50
github.com/dymensionxyz/rollapp-evm/cmd/rollappd/cmd.wrapCPUProfile.func2()
	/Users/sergi/workspace/dymension/rollapp-evm-2/cmd/rollappd/cmd/start.go:663 +0x30
created by github.com/dymensionxyz/rollapp-evm/cmd/rollappd/cmd.wrapCPUProfile in goroutine 1
	/Users/sergi/workspace/dymension/rollapp-evm-2/cmd/rollappd/cmd/start.go:662 +0x1d0

**Comment by srene** [comment]
This error happens when a full-node starts while celestia is out of sync
