### ISSUE TITLE
Investigate mempool test panic

### ISSUE THREAD

**Issue by danwt** [dymensionxyz/dymint#897]
https://github.com/dymensionxyz/dymint/pull/889#issuecomment-2145242045
https://github.com/dymensionxyz/dymint/actions/runs/9351213453/job/25736400514?pr=889

```
D[2024-06-03|13:39:09.224] Applying block                               module=BlockManager height=2 source=produced
I[2024-06-03|13:39:09.226] Block created.                               module=BlockManager height=2 num_tx=0
D[2024-06-03|13:39:09.227] indexed block                                module=txindex height=2
D[2024-06-03|13:39:09.227] indexed block txs                            module=txindex height=2 num_txs=0
D[2024-06-03|13:39:09.227] Gossiping block.                             module=p2p len=730
I[2024-06-03|13:39:09.228] Produced empty block.                        module=BlockManager 
I[2024-06-03|13:39:09.228] New batch accumulated, sent signal to submit the batch. module=BlockManager 
D[2024-06-03|13:39:09.229] Submitting batch to DA layer                 module=mock startheight=1 endheight=1 daheight=1
I[2024-06-03|13:39:09.229] Submitted batch to DA                        module=BlockManager startheight=1 endheight=1
D[2024-06-03|13:39:09.229] Saving batch to settlement layer.            module=settlement_client startheight=1 endheight=1
panic: handle submission trigger: sl client submit batch: start height: 1: inclusive end height: 1: Writes are blocked, possibly due to DropAll or Close

goroutine 91 [running]:
github.com/dymensionxyz/dymint/block.(*Manager).SubmitLoop(0xc000116b00, {0x3737790, 0x5a067a0})
	/home/runner/work/dymint/dymint/block/submit.go:58 +0x5aa
created by github.com/dymensionxyz/dymint/block.(*Manager).Start in goroutine 52
	/home/runner/work/dymint/dymint/block/manager.go:167 +0x8ef
FAIL	github.com/dymensionxyz/dymint/node	0.329s
FAIL
exit status 1
```

**Comment by danwt** [comment]
Need to close as not sure which test exactly
